import type { Department, Doctor, Hospital, HospitalFeedback, Patient, Appointment } from '../src/types.ts';
import bcrypt from 'bcryptjs';

export interface Admin {
  id: number;
  username: string;
  password: string;
}

export const initialDepartments: Department[] = [
  { id: 1, department_name: 'Cardiology', icon: 'Heart', description: 'Comprehensive cardiac care, interventional angioplasty, electrophysiology, and bypass surgery.' },
  { id: 2, department_name: 'Neurology & Neurosurgery', icon: 'Brain', description: 'Level 1 stroke center, stereotactic neurosurgery, neuro-rehabilitation, and spine care.' },
  { id: 3, department_name: 'Orthopedics & Joint Care', icon: 'Bone', description: 'Robotic joint replacement, arthroscopy, sports medicine, and polytrauma reconstruction.' },
  { id: 4, department_name: 'Pediatrics & Neonatology', icon: 'Baby', description: 'Level III NICU, pediatric cardiology, critical care, and developmental medicine.' },
  { id: 5, department_name: 'Gynecology & Obstetrics', icon: 'Activity', description: 'High-risk pregnancy management, fetal medicine, laparoscopic and robotic gynecology.' },
  { id: 6, department_name: 'General & Robotic Surgery', icon: 'Scissors', description: 'Minimally invasive laparoscopic, robotic gastrointestinal, bariatric, and oncology surgery.' },
  { id: 7, department_name: 'Internal Medicine & Diabetology', icon: 'Stethoscope', description: 'Comprehensive adult health, chronic illness, diabetology, and clinical immunology.' },
  { id: 8, department_name: 'ENT & Head Neck Surgery', icon: 'Ear', description: 'Cochlear implants, endoscopic sinus surgery, voice clinic, and skull base surgery.' },
  { id: 9, department_name: 'Dermatology & Cosmetology', icon: 'Shield', description: 'Clinical dermatology, laser surgery, dermato-pathology, and aesthetic dermatology.' }
];

const allDeptNames = initialDepartments.map(d => d.department_name);

export const initialHospitals: Hospital[] = [
  {
    id: 1,
    name: 'RH Care Multi-Specialty Hospital - Central Campus',
    tagline: 'Flagship Quaternary Healthcare & Advanced Research Campus',
    address: '14/2, 100 Feet Road, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560038',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560038',
    latitude: 12.971891,
    longitude: 77.641151,
    phone: '+91 (080) 4968-1000',
    emergency_hotline: '+91 (080) 4968-1999',
    rating: 4.92,
    review_count: 1840,
    beds_count: 650,
    icu_beds: 120,
    trauma_level: 'Level 1 Comprehensive Trauma Center',
    accreditations: ['JCI Gold Seal International', 'NABH Digital & Hospital Standard', 'NABL Certified Diagnostic Lab', 'Green OT Accredited'],
    facilities: [
      '24/7 Level 1 Trauma & Emergency Care',
      'DaVinci Xi Robotic Surgical System',
      'Dedicated Biplane Cardiac & Neuro Cath Labs',
      '3T Vida Digital MRI & Dual-Source 128-Slice CT',
      'Multi-Organ Transplant Unit (Liver, Kidney, Heart)',
      'Automated Round-the-Clock Blood Bank',
      'Air Ambulance Rooftop Helipad'
    ],
    operating_hours: '24 Hours Open (Emergency & Inpatient) • OPD: 08:30 AM - 08:00 PM',
    departments: allDeptNames,
    image_url: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 2,
    name: 'RH Care Heart & Vascular Institute - East Wing',
    tagline: 'Center of Excellence in Cardiovascular & Thoracic Sciences',
    address: '88, ITPL Main Road, EPIP Zone, Whitefield, Bengaluru, Karnataka 560066',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560066',
    latitude: 12.986420,
    longitude: 77.728140,
    phone: '+91 (080) 4652-2000',
    emergency_hotline: '+91 (080) 4652-2108',
    rating: 4.94,
    review_count: 1420,
    beds_count: 450,
    icu_beds: 95,
    trauma_level: 'Level 1 Cardiac & Vascular Emergency Center',
    accreditations: ['JCI Gold Seal Accreditation', 'NABH Cardiac Speciality', 'AHA Gold Plus Award'],
    facilities: [
      '24/7 Acute Chest Pain & STEMI Rapid Angioplasty Unit',
      '3 Fully Equipped Hybrid Cardiac Operating Theatres',
      'Extracorporeal Membrane Oxygenation (ECMO) Care Unit',
      'Cardiovascular Genetic Risk Profiling Clinic',
      'Outpatient Cardiac Fitness & Rehabilitation Center'
    ],
    operating_hours: '24 Hours Open • OPD: 09:00 AM - 07:30 PM',
    departments: allDeptNames,
    image_url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 3,
    name: 'RH Care Super-Specialty Medical City - North',
    tagline: 'Quaternary Trauma, Cancer, and Neurosciences Complex',
    address: 'Sector 3, Bellary Road, Near Hebbal Lake, Bengaluru, Karnataka 560024',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560024',
    latitude: 13.035840,
    longitude: 77.597022,
    phone: '+91 (080) 4310-3000',
    emergency_hotline: '+91 (080) 4310-3911',
    rating: 4.88,
    review_count: 2150,
    beds_count: 750,
    icu_beds: 150,
    trauma_level: 'Level 1 Polytrauma, Burn & Neuro Center',
    accreditations: ['JCI Accredited', 'NABH Comprehensive Healthcare', 'ISO 9001:2015 Quality certified'],
    facilities: [
      '24/7 Red-Alert Polytrauma Resuscitation Center',
      'CyberKnife & TrueBeam Linear Accelerator Radiotherapy',
      'Comprehensive Bone Marrow & Stem Cell Transplant',
      '4K Laparoscopic & Robotic Gastrointestinal Suites',
      'Specialized Adult, Pediatric & Neonatal ICUs'
    ],
    operating_hours: '24 Hours Open • OPD: 08:00 AM - 08:30 PM',
    departments: allDeptNames,
    image_url: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 4,
    name: "RH Care Women & Children's Super-Specialty Hospital - South",
    tagline: 'Dedicated Institute for High-Risk Maternity, Fetal Medicine & Pediatrics',
    address: '24, 100 Feet Ring Road, 4th T Block, Jayanagar, Bengaluru, Karnataka 560011',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560011',
    latitude: 12.929820,
    longitude: 77.583310,
    phone: '+91 (080) 4780-4000',
    emergency_hotline: '+91 (080) 4780-4999',
    rating: 4.95,
    review_count: 1670,
    beds_count: 350,
    icu_beds: 65,
    trauma_level: 'Level 1 Obstetric & Pediatric Emergency Unit',
    accreditations: ['NABH Specialized Maternal Care', 'UNICEF Baby-Friendly Initiative', 'FMF Certified Fetal Medicine'],
    facilities: [
      'Level III Advanced 50-Bed Neonatal ICU (NICU)',
      'Pediatric Intensive Care Unit (PICU) with ECMO',
      'LDR (Labor, Delivery, Recovery) Private Suites',
      'Advanced Fetal Echocardiography & Genetic Testing',
      '24/7 Pediatric Emergency with Dedicated Resuscitation'
    ],
    operating_hours: '24 Hours Open • OPD: 09:00 AM - 07:00 PM',
    departments: allDeptNames,
    image_url: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 5,
    name: 'RH Care Institute of Neurosciences & Orthopedics - West',
    tagline: 'Leading Center for Brain, Spine, and Robotic Joint Reconstruction',
    address: '56, Dr. Rajkumar Road, 2nd Block, Rajajinagar, Bengaluru, Karnataka 560010',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560010',
    latitude: 12.998240,
    longitude: 77.553020,
    phone: '+91 (080) 4590-5000',
    emergency_hotline: '+91 (080) 4590-5999',
    rating: 4.89,
    review_count: 1120,
    beds_count: 400,
    icu_beds: 80,
    trauma_level: 'Level 1 Neuro-Spinal & Orthopedic Trauma',
    accreditations: ['NABH Accreditation', 'World Stroke Organization Platinum Center'],
    facilities: [
      '24/7 Code Stroke Emergency Resuscitation Team',
      'Intraoperative 3T Brain Suite & StealthStation Navigation',
      'MAKO SmartRobotics for Total Knee & Hip Arthroplasty',
      'Comprehensive Hydrotherapy & Neuro-Rehabilitation Gym',
      'Digital Motion Analysis & Sports Injury Laboratory'
    ],
    operating_hours: '24 Hours Open • OPD: 08:30 AM - 08:00 PM',
    departments: allDeptNames,
    image_url: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=1200&q=80'
  }
];

export const initialFeedbacks: HospitalFeedback[] = [
  {
    id: 1,
    hospital_id: 1,
    patient_name: 'Suresh Narayanan',
    treatment: 'Emergency Primary Angioplasty & 2 Drug-Eluting Stents',
    doctor_name: 'Dr. R. Rajeshwar, MD, DM',
    rating: 5,
    review_date: '2026-09-18',
    verified: true,
    comment: 'When I experienced sudden severe chest discomfort, the RH Care Emergency team at Central Campus was phenomenal. From arrival to the Cath Lab door was under 18 minutes! Dr. Rajeshwar explained every step with absolute calmness and empathy.'
  },
  {
    id: 2,
    hospital_id: 1,
    patient_name: 'Meena Balakrishnan',
    treatment: 'Robotic Bilateral Knee Replacement',
    doctor_name: 'Dr. Harini V. Sundaram, MS, MCh, FRCS',
    rating: 5,
    review_date: '2026-09-12',
    verified: true,
    comment: 'I had been struggling with severe osteoarthritis for 7 years. Dr. Harini used the robotic navigation system and I was walking with minimal support on Day 2! The nursing staff in Floor 5 are angels.'
  },
  {
    id: 3,
    hospital_id: 2,
    patient_name: 'Karthik Somayaji',
    treatment: 'Complex Cardiac Electrophysiology & Cryo-Ablation',
    doctor_name: 'Dr. Priya S. Nambiar, MD, DM',
    rating: 5,
    review_date: '2026-09-20',
    verified: true,
    comment: 'The East Wing Heart Institute is world class. Everything is ultra-modern and organized. Dr. Priya diagnosed my arrhythmia within minutes and the ablation procedure completely eliminated my palpitations.'
  },
  {
    id: 4,
    hospital_id: 3,
    patient_name: 'Anita Fernandez',
    treatment: 'Robotic Laparoscopic Cholecystectomy',
    doctor_name: 'Dr. Vikramaditya Reddy, MS, MCh, FRCS',
    rating: 5,
    review_date: '2026-09-15',
    verified: true,
    comment: 'Underwent robotic gall bladder surgery with Dr. Vikramaditya at North Medical City. Virtually painless post-op recovery, zero scar visible, and discharged in less than 24 hours. Superb coordination.'
  },
  {
    id: 5,
    hospital_id: 4,
    patient_name: 'Divya & Rohan Varma',
    treatment: 'High-Risk Twin Delivery & Level III NICU Care',
    doctor_name: 'Dr. Suniti Deshmukh & Dr. Ananya Sengupta',
    rating: 5,
    review_date: '2026-09-10',
    verified: true,
    comment: 'Our twins arrived at 32 weeks. The NICU facilities, sterile incubators, and Dr. Ananya’s daily updates gave us immense strength. Today our babies are thriving at home! RH Care is truly a blessing.'
  },
  {
    id: 6,
    hospital_id: 5,
    patient_name: 'Chandrashekar Gowda',
    treatment: 'Endoscopic Lumbar Microdiscectomy',
    doctor_name: 'Dr. Alok Chandra, MS (Ortho), Spine Fellow',
    rating: 5,
    review_date: '2026-09-14',
    verified: true,
    comment: 'My debilitating sciatica pain was gone the moment I woke up from anesthesia. Dr. Alok Chandra is gifted, compassionate, and takes time to answer every question. Highly recommend the West Institute.'
  }
];

// Complete 45 Verified Specialists across all 5 hospitals and 9 clinical departments
export const initialDoctors: Doctor[] = [
  // ==========================================
  // CAMPUS 1: Central Campus (Indiranagar)
  // ==========================================
  {
    id: 1,
    doctor_name: 'Dr. R. Rajeshwar',
    degrees: 'MBBS, MD (Gen Med), DM (Cardiology) - AIIMS, FACC (USA)',
    department_id: 1,
    department_name: 'Cardiology',
    hospital_id: 1,
    hospital_name: 'RH Care Multi-Specialty Hospital - Central Campus',
    specialization: 'Director & Chief Interventional Cardiologist',
    sub_specialties: ['Complex Coronary Angioplasty', 'Transcatheter Aortic Valve Implantation (TAVI)', 'Bifurcation Stenting', 'Radial Access Angiography'],
    experience_years: 22,
    opd_timings: '09:30 AM - 01:30 PM (Mon - Sat)',
    room_number: 'Cardiac Wing - Suite 101',
    consultation_fee: 1000,
    languages: ['English', 'Hindi', 'Kannada', 'Tamil'],
    rating: 4.96,
    total_patients: 18500,
    bio: 'Pioneer in radial coronary interventions with over 15,000 successful procedures. Fellow of American College of Cardiology.',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 2,
    doctor_name: 'Dr. Arvind Swaminathan',
    degrees: 'MBBS, MD (Medicine), DM (Neurology) - NIMHANS, FINR',
    department_id: 2,
    department_name: 'Neurology & Neurosurgery',
    hospital_id: 1,
    hospital_name: 'RH Care Multi-Specialty Hospital - Central Campus',
    specialization: 'Senior Consultant Neurologist & Neurovascular Specialist',
    sub_specialties: ['Stroke Management', 'Epilepsy Monitoring', 'Migraine & Chronic Headache Care'],
    experience_years: 17,
    opd_timings: '10:00 AM - 02:00 PM (Mon - Sat)',
    room_number: 'Neuro OPD - Suite 203',
    consultation_fee: 950,
    languages: ['English', 'Kannada', 'Tamil', 'Hindi'],
    rating: 4.93,
    total_patients: 12100,
    bio: 'Dedicated neurovascular physician specializing in acute stroke revascularization and neuro-critical recovery.',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 3,
    doctor_name: 'Dr. Harini V. Sundaram',
    degrees: 'MBBS, MS (Orthopedics), MCh (Joint Replacement), FRCS (Edin)',
    department_id: 3,
    department_name: 'Orthopedics & Joint Care',
    hospital_id: 1,
    hospital_name: 'RH Care Multi-Specialty Hospital - Central Campus',
    specialization: 'Chief Robotic Joint Replacement & Arthroscopic Surgeon',
    sub_specialties: ['Robotic Total Knee Arthroplasty', 'Direct Anterior Hip Replacement', 'ACL / PCL Ligament Reconstruction', 'Cartilage Regeneration'],
    experience_years: 18,
    opd_timings: '09:00 AM - 01:00 PM (Mon - Fri)',
    room_number: 'Ortho Tower - Suite 305',
    consultation_fee: 950,
    languages: ['English', 'Tamil', 'Kannada', 'Hindi'],
    rating: 4.95,
    total_patients: 14200,
    bio: 'Pioneered sub-millimeter robotic-assisted knee and hip arthroplasty with zero bone sacrifice. Over 6,000 successful joint replacements.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 4,
    doctor_name: 'Dr. Rohini Sen',
    degrees: 'MBBS, MD (Pediatrics), Fellowship in Pediatric Intensive Care',
    department_id: 4,
    department_name: 'Pediatrics & Neonatology',
    hospital_id: 1,
    hospital_name: 'RH Care Multi-Specialty Hospital - Central Campus',
    specialization: 'Senior Pediatrician & Child Health Consultant',
    sub_specialties: ['Child Immunization', 'Pediatric Nutrition', 'Allergy & Asthma Management'],
    experience_years: 14,
    opd_timings: '09:00 AM - 01:00 PM (Mon - Fri)',
    room_number: 'Pediatric Clinic - Suite 102',
    consultation_fee: 800,
    languages: ['English', 'Hindi', 'Bengali', 'Kannada'],
    rating: 4.91,
    total_patients: 9500,
    bio: 'Comprehensive child specialist focusing on newborn care, immunization regimens, and developmental health.',
    image: 'https://images.unsplash.com/photo-1594824813576-24869c98687b?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 5,
    doctor_name: 'Dr. Malini Rao',
    degrees: 'MBBS, MS (OBG), DNB, Fellow in Minimally Invasive Gynecology',
    department_id: 5,
    department_name: 'Gynecology & Obstetrics',
    hospital_id: 1,
    hospital_name: 'RH Care Multi-Specialty Hospital - Central Campus',
    specialization: 'Senior Consultant Obstetrician & Gynecologist',
    sub_specialties: ['Antenatal Care', 'Laparoscopic Hysterectomy', 'PCOS Management', 'Fertility Workup'],
    experience_years: 16,
    opd_timings: '11:00 AM - 03:30 PM (Mon - Sat)',
    room_number: 'Women’s Health - Suite 208',
    consultation_fee: 850,
    languages: ['English', 'Kannada', 'Hindi', 'Telugu'],
    rating: 4.94,
    total_patients: 13000,
    bio: 'Compassionate women’s health expert with extensive surgical experience in complex gynecological care.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 6,
    doctor_name: 'Dr. Vikramaditya Reddy',
    degrees: 'MBBS, MS (General Surgery), MCh (Surgical Oncology), FRCS, FACS',
    department_id: 6,
    department_name: 'General & Robotic Surgery',
    hospital_id: 1,
    hospital_name: 'RH Care Multi-Specialty Hospital - Central Campus',
    specialization: 'Head of Department - Robotic & Minimal Access Surgical Sciences',
    sub_specialties: ['DaVinci Robotic Abdominal Surgery', 'Advanced Laparoscopic Gastrointestinal Surgery', 'Hernia Reconstruction'],
    experience_years: 23,
    opd_timings: '08:30 AM - 12:30 PM (Mon - Fri)',
    room_number: 'Surgical Block - Suite 105',
    consultation_fee: 1000,
    languages: ['English', 'Telugu', 'Hindi', 'Kannada'],
    rating: 4.95,
    total_patients: 17800,
    bio: 'International Proctor for DaVinci Xi Robotic Surgery with over 4,000 console surgical cases performed.',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 7,
    doctor_name: 'Dr. Pradeep Joshi',
    degrees: 'MBBS, MD (Internal Medicine), FACP (USA)',
    department_id: 7,
    department_name: 'Internal Medicine & Diabetology',
    hospital_id: 1,
    hospital_name: 'RH Care Multi-Specialty Hospital - Central Campus',
    specialization: 'Senior Consultant Physician & Diabetologist',
    sub_specialties: ['Diabetic Foot Care', 'Hypertension & Lipid Disorders', 'Geriatric Medicine'],
    experience_years: 19,
    opd_timings: '08:30 AM - 01:00 PM (Mon - Sat)',
    room_number: 'Medicine Wing - Suite 104',
    consultation_fee: 800,
    languages: ['English', 'Hindi', 'Marathi', 'Kannada'],
    rating: 4.89,
    total_patients: 16000,
    bio: 'Senior internist delivering preventative health checks, glycemic control, and metabolic wellness.',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 8,
    doctor_name: 'Dr. Gautam Bansal',
    degrees: 'MBBS, MS (ENT), DNB',
    department_id: 8,
    department_name: 'ENT & Head Neck Surgery',
    hospital_id: 1,
    hospital_name: 'RH Care Multi-Specialty Hospital - Central Campus',
    specialization: 'Senior ENT Surgeon & Sinus Specialist',
    sub_specialties: ['Functional Endoscopic Sinus Surgery (FESS)', 'Tympanoplasty', 'Tonsil & Adenoid Surgery'],
    experience_years: 13,
    opd_timings: '02:00 PM - 06:00 PM (Mon - Sat)',
    room_number: 'ENT Suite - Room 215',
    consultation_fee: 750,
    languages: ['English', 'Hindi', 'Kannada'],
    rating: 4.90,
    total_patients: 8800,
    bio: 'Specialist in microscopic ear surgery, allergy-induced sinusitis, and endoscopic airway interventions.',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 9,
    doctor_name: 'Dr. Tanvi Kapoor',
    degrees: 'MBBS, MD (Dermatology & Cosmetology)',
    department_id: 9,
    department_name: 'Dermatology & Cosmetology',
    hospital_id: 1,
    hospital_name: 'RH Care Multi-Specialty Hospital - Central Campus',
    specialization: 'Senior Consultant Dermatologist & Laser Specialist',
    sub_specialties: ['Acne Scar Revision', 'Anti-Aging Therapies', 'Eczema & Psoriasis Protocols'],
    experience_years: 11,
    opd_timings: '10:30 AM - 03:00 PM (Mon - Fri)',
    room_number: 'Derma Suite - Room 302',
    consultation_fee: 750,
    languages: ['English', 'Hindi', 'Punjabi'],
    rating: 4.92,
    total_patients: 8100,
    bio: 'Evidence-based clinician in clinical dermatology and advanced restorative skincare.',
    image: 'https://images.unsplash.com/photo-1594824813576-24869c98687b?auto=format&fit=crop&w=600&q=80'
  },

  // ==========================================
  // CAMPUS 2: East Wing Heart & Vascular (Whitefield)
  // ==========================================
  {
    id: 10,
    doctor_name: 'Dr. Priya S. Nambiar',
    degrees: 'MBBS, MD (Gen Med), DM (Cardiology), Fellowship in Electrophysiology',
    department_id: 1,
    department_name: 'Cardiology',
    hospital_id: 2,
    hospital_name: 'RH Care Heart & Vascular Institute - East Wing',
    specialization: 'Senior Cardiac Electrophysiologist & Pacing Specialist',
    sub_specialties: ['3D Arrhythmia Mapping', 'Cryo-Ablation', 'ICD & Pacemaker Implantation', 'Heart Failure Sync'],
    experience_years: 15,
    opd_timings: '10:00 AM - 02:00 PM (Mon - Fri)',
    room_number: 'Heart Tower - Suite 204',
    consultation_fee: 900,
    languages: ['English', 'Malayalam', 'Hindi', 'Kannada'],
    rating: 4.92,
    total_patients: 9800,
    bio: 'Recognized authority in cardiac rhythm management, conduction system pacing, and catheter ablation.',
    image: 'https://images.unsplash.com/photo-1594824813576-24869c98687b?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 11,
    doctor_name: 'Dr. Farooq A. Qureshi',
    degrees: 'MBBS, MD (Pediatrics), Fellowship in Pediatric Cardiology',
    department_id: 4,
    department_name: 'Pediatrics & Neonatology',
    hospital_id: 2,
    hospital_name: 'RH Care Heart & Vascular Institute - East Wing',
    specialization: 'Senior Pediatric Cardiologist & Congenital Heart Defect Specialist',
    sub_specialties: ['ASD / VSD / PDA Device Closure', 'Neonatal Balloon Valvuloplasty', 'Pediatric Echocardiography'],
    experience_years: 14,
    opd_timings: '09:00 AM - 01:00 PM (Mon - Sat)',
    room_number: 'Pediatric Heart Clinic - Suite 104',
    consultation_fee: 900,
    languages: ['English', 'Urdu', 'Hindi', 'Kannada'],
    rating: 4.94,
    total_patients: 8900,
    bio: 'Dedicated to curing congenital heart defects in infants and young children through non-surgical device closure.',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 12,
    doctor_name: 'Dr. Deepak N. Varma',
    degrees: 'MBBS, MD (Medicine), Postgrad Diploma in Diabetology',
    department_id: 7,
    department_name: 'Internal Medicine & Diabetology',
    hospital_id: 2,
    hospital_name: 'RH Care Heart & Vascular Institute - East Wing',
    specialization: 'Senior Consultant Physician & Cardiovascular Diabetologist',
    sub_specialties: ['Cardiometabolic Syndrome', 'Resistant Hypertension', 'Dyslipidemia Management'],
    experience_years: 18,
    opd_timings: '09:30 AM - 01:30 PM (Mon - Sat)',
    room_number: 'East Clinic - Room 106',
    consultation_fee: 800,
    languages: ['English', 'Hindi', 'Malayalam', 'Kannada'],
    rating: 4.90,
    total_patients: 14500,
    bio: 'Specialist in managing metabolic syndrome, diabetes-associated cardiovascular complications, and preventative medicine.',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 13,
    doctor_name: 'Dr. Rajiv Menon',
    degrees: 'MBBS, MS (Orthopedics), Fellow in Sports Medicine & Arthroscopy',
    department_id: 3,
    department_name: 'Orthopedics & Joint Care',
    hospital_id: 2,
    hospital_name: 'RH Care Heart & Vascular Institute - East Wing',
    specialization: 'Senior Orthopedic & Sports Medicine Consultant',
    sub_specialties: ['Knee Arthroscopy', 'Shoulder Rotator Cuff Repair', 'Sports Injury Rehabilitation'],
    experience_years: 15,
    opd_timings: '02:00 PM - 06:30 PM (Mon - Fri)',
    room_number: 'East Suite - Room 202',
    consultation_fee: 850,
    languages: ['English', 'Malayalam', 'Kannada', 'Hindi'],
    rating: 4.88,
    total_patients: 10400,
    bio: 'Focuses on rapid rehabilitation for ligament injuries, robotic joint assessment, and sports surgery.',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 14,
    doctor_name: 'Dr. Ananya Mathur',
    degrees: 'MBBS, DM (Neurology), Fellowship in Neuro-Vascular Diagnostics',
    department_id: 2,
    department_name: 'Neurology & Neurosurgery',
    hospital_id: 2,
    hospital_name: 'RH Care Heart & Vascular Institute - East Wing',
    specialization: 'Senior Neurovascular Physician & Stroke Specialist',
    sub_specialties: ['Cerebral Angiography', 'Transient Ischemic Attacks', 'Syncope & Autonomic Disorders'],
    experience_years: 13,
    opd_timings: '10:00 AM - 02:00 PM (Mon - Sat)',
    room_number: 'Neuro Lab - Suite 108',
    consultation_fee: 900,
    languages: ['English', 'Hindi', 'Kannada'],
    rating: 4.91,
    total_patients: 9100,
    bio: 'Expertise in neuro-cardiac interactions, brain perfusion analysis, and preventive stroke therapy.',
    image: 'https://images.unsplash.com/photo-1594824813576-24869c98687b?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 15,
    doctor_name: 'Dr. Sunita K. Hegde',
    degrees: 'MBBS, MS (OBG), DNB',
    department_id: 5,
    department_name: 'Gynecology & Obstetrics',
    hospital_id: 2,
    hospital_name: 'RH Care Heart & Vascular Institute - East Wing',
    specialization: 'Senior Obstetrician & Women’s Health Consultant',
    sub_specialties: ['Cardiac Health in Pregnancy', 'Pre-Eclampsia Care', 'Menopause Care'],
    experience_years: 17,
    opd_timings: '09:00 AM - 01:00 PM (Mon - Sat)',
    room_number: 'East Women Suite - Room 205',
    consultation_fee: 800,
    languages: ['English', 'Kannada', 'Hindi'],
    rating: 4.93,
    total_patients: 11400,
    bio: 'Specialist in multi-disciplinary high-risk maternal care with cardiac comorbidities.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 16,
    doctor_name: 'Dr. S. K. Bhattacharya',
    degrees: 'MBBS, MS (General Surgery), MCh (Vascular Surgery)',
    department_id: 6,
    department_name: 'General & Robotic Surgery',
    hospital_id: 2,
    hospital_name: 'RH Care Heart & Vascular Institute - East Wing',
    specialization: 'Chief Peripheral Vascular & Minimally Invasive Surgeon',
    sub_specialties: ['Aortic Aneurysm Repair', 'Carotid Endarterectomy', 'Varicose Vein Laser Surgery'],
    experience_years: 21,
    opd_timings: '11:00 AM - 03:00 PM (Mon - Fri)',
    room_number: 'Vascular Wing - Suite 301',
    consultation_fee: 950,
    languages: ['English', 'Bengali', 'Hindi'],
    rating: 4.95,
    total_patients: 13700,
    bio: 'Performed over 5,000 limb salvage procedures and hybrid endovascular aortic repairs.',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 17,
    doctor_name: 'Dr. Ramesh Naidu',
    degrees: 'MBBS, MS (ENT), Fellowship in Head & Neck Surgery',
    department_id: 8,
    department_name: 'ENT & Head Neck Surgery',
    hospital_id: 2,
    hospital_name: 'RH Care Heart & Vascular Institute - East Wing',
    specialization: 'Senior ENT Surgeon',
    sub_specialties: ['Sleep Apnea Coblation', 'Vocal Cord Microsurgery', 'Sinus Endoscopy'],
    experience_years: 12,
    opd_timings: '03:00 PM - 07:00 PM (Mon - Sat)',
    room_number: 'East ENT - Room 109',
    consultation_fee: 750,
    languages: ['English', 'Telugu', 'Kannada', 'Hindi'],
    rating: 4.89,
    total_patients: 8300,
    bio: 'Clinical specialist in airway disorders, chronic snoring treatments, and allergy therapies.',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 18,
    doctor_name: 'Dr. Nidhi Singhal',
    degrees: 'MBBS, MD (Dermatology)',
    department_id: 9,
    department_name: 'Dermatology & Cosmetology',
    hospital_id: 2,
    hospital_name: 'RH Care Heart & Vascular Institute - East Wing',
    specialization: 'Consultant Dermatologist & Laser Surgeon',
    sub_specialties: ['Laser Skin Resurfacing', 'Pigmentation Disorders', 'Cutaneous Allergy'],
    experience_years: 10,
    opd_timings: '10:00 AM - 02:00 PM (Tue - Sat)',
    room_number: 'East Derma - Room 114',
    consultation_fee: 700,
    languages: ['English', 'Hindi', 'Kannada'],
    rating: 4.90,
    total_patients: 7500,
    bio: 'Expert in medical aesthetics, allergy patch testing, and laser therapies for skin rejuvenation.',
    image: 'https://images.unsplash.com/photo-1594824813576-24869c98687b?auto=format&fit=crop&w=600&q=80'
  },

  // ==========================================
  // CAMPUS 3: Super-Specialty Medical City - North (Hebbal)
  // ==========================================
  {
    id: 19,
    doctor_name: 'Dr. Sandeep K. Mehta',
    degrees: 'MBBS, MD (Medicine), DM (Neurology), DNB, MRCP (Neurology - UK)',
    department_id: 2,
    department_name: 'Neurology & Neurosurgery',
    hospital_id: 3,
    hospital_name: 'RH Care Super-Specialty Medical City - North',
    specialization: 'Director of Neurosciences & Comprehensive Stroke Institute',
    sub_specialties: ['Hyper-Acute Ischemic Stroke Thrombolysis', 'Intractable Epilepsy Management', 'Movement Disorders & DBS'],
    experience_years: 20,
    opd_timings: '10:00 AM - 02:30 PM (Mon - Sat)',
    room_number: 'Neuroscience Center - Suite 401',
    consultation_fee: 1000,
    languages: ['English', 'Hindi', 'Gujarati', 'Kannada'],
    rating: 4.94,
    total_patients: 16000,
    bio: 'Leads the accredited 24/7 Code Stroke Emergency Team with an average door-to-needle time of 22 minutes.',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 20,
    doctor_name: 'Dr. Bhaskar Chander',
    degrees: 'MBBS, MD (Medicine), DM (Cardiology), FESC',
    department_id: 1,
    department_name: 'Cardiology',
    hospital_id: 3,
    hospital_name: 'RH Care Super-Specialty Medical City - North',
    specialization: 'Senior Interventional Cardiologist',
    sub_specialties: ['Primary Angioplasty', 'Heart Failure Device Therapy', 'Echocardiography'],
    experience_years: 18,
    opd_timings: '10:00 AM - 02:00 PM (Mon - Sat)',
    room_number: 'North Cardiology - Suite 105',
    consultation_fee: 900,
    languages: ['English', 'Hindi', 'Kannada'],
    rating: 4.93,
    total_patients: 13800,
    bio: 'Extensive background in complex coronary interventions and advanced preventative cardiology.',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 21,
    doctor_name: 'Dr. Suresh N. Kulkarni',
    degrees: 'MBBS, MS (Orthopedics), Fellowship in Complex Trauma & Arthroplasty',
    department_id: 3,
    department_name: 'Orthopedics & Joint Care',
    hospital_id: 3,
    hospital_name: 'RH Care Super-Specialty Medical City - North',
    specialization: 'Director of Polytrauma & Robotic Orthopedic Surgery',
    sub_specialties: ['Pelvic & Acetabular Fractures', 'Revision Joint Replacement', 'Complex Polytrauma'],
    experience_years: 21,
    opd_timings: '09:00 AM - 01:30 PM (Mon - Fri)',
    room_number: 'Ortho Suite - Room 308',
    consultation_fee: 950,
    languages: ['English', 'Marathi', 'Kannada', 'Hindi'],
    rating: 4.96,
    total_patients: 15400,
    bio: 'Renowned expert in reconstruction of polytrauma victims and robotic-assisted total hip and knee revision surgeries.',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 22,
    doctor_name: 'Dr. Amitava Ghosh',
    degrees: 'MBBS, MS (Surgery), MCh (Surgical Gastro), FRCS (Edin)',
    department_id: 6,
    department_name: 'General & Robotic Surgery',
    hospital_id: 3,
    hospital_name: 'RH Care Super-Specialty Medical City - North',
    specialization: 'Senior Consultant Gastrointestinal & Laparoscopic Surgeon',
    sub_specialties: ['Laparoscopic Colorectal Surgery', 'Hepato-Biliary Surgery', 'Hernia Repair'],
    experience_years: 19,
    opd_timings: '11:00 AM - 03:00 PM (Mon - Sat)',
    room_number: 'Surgery Pavilion - Suite 204',
    consultation_fee: 900,
    languages: ['English', 'Bengali', 'Hindi'],
    rating: 4.91,
    total_patients: 12900,
    bio: 'Senior gastrointestinal surgeon specializing in scarless keyhole surgery and complex abdominal re-explorations.',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 23,
    doctor_name: 'Dr. Shalini Balakrishnan',
    degrees: 'MBBS, MD (Internal Medicine), DNB (Endocrinology & Diabetology)',
    department_id: 7,
    department_name: 'Internal Medicine & Diabetology',
    hospital_id: 3,
    hospital_name: 'RH Care Super-Specialty Medical City - North',
    specialization: 'Senior Consultant Physician & Diabetologist',
    sub_specialties: ['Advanced Diabetes Management', 'Insulin Pump Therapy', 'Thyroid Disorders'],
    experience_years: 13,
    opd_timings: '09:00 AM - 01:30 PM (Mon - Sat)',
    room_number: 'Internal Medicine Wing - Suite 302',
    consultation_fee: 750,
    languages: ['English', 'Tamil', 'Hindi', 'Kannada'],
    rating: 4.88,
    total_patients: 12400,
    bio: 'Expertise in reversing early metabolic syndromes, continuous glucose monitoring, and internal medicine.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 24,
    doctor_name: 'Dr. Arun K. Raghavan',
    degrees: 'MBBS, MS (ENT), Fellowship in Cochlear Implants (Sydney)',
    department_id: 8,
    department_name: 'ENT & Head Neck Surgery',
    hospital_id: 3,
    hospital_name: 'RH Care Super-Specialty Medical City - North',
    specialization: 'Chief of ENT, Cochlear Implant & Skull Base Surgery',
    sub_specialties: ['Endoscopic Sinus Surgery (FESS)', 'Cochlear Implantation', 'Sleep Apnea Surgery'],
    experience_years: 16,
    opd_timings: '02:30 PM - 06:30 PM (Mon - Sat)',
    room_number: 'ENT Center - Suite 210',
    consultation_fee: 800,
    languages: ['English', 'Malayalam', 'Kannada', 'Hindi'],
    rating: 4.91,
    total_patients: 10500,
    bio: 'Performed over 600 successful cochlear implants restoring hearing in pediatric and adult patients.',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 25,
    doctor_name: 'Dr. Kiranmayi Prasad',
    degrees: 'MBBS, MD (Pediatrics), Fellowship in Pediatric Critical Care',
    department_id: 4,
    department_name: 'Pediatrics & Neonatology',
    hospital_id: 3,
    hospital_name: 'RH Care Super-Specialty Medical City - North',
    specialization: 'Senior Consultant Pediatrician',
    sub_specialties: ['Pediatric Emergency Resuscitation', 'Infectious Diseases', 'Child Growth Care'],
    experience_years: 14,
    opd_timings: '09:30 AM - 01:30 PM (Mon - Sat)',
    room_number: 'North Pediatric - Room 103',
    consultation_fee: 750,
    languages: ['English', 'Kannada', 'Telugu', 'Hindi'],
    rating: 4.90,
    total_patients: 9800,
    bio: 'Compassionate care for pediatric emergencies and developmental pediatrics.',
    image: 'https://images.unsplash.com/photo-1594824813576-24869c98687b?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 26,
    doctor_name: 'Dr. Radhika Sen',
    degrees: 'MBBS, MS (OBG), Fellowship in Fetal Medicine',
    department_id: 5,
    department_name: 'Gynecology & Obstetrics',
    hospital_id: 3,
    hospital_name: 'RH Care Super-Specialty Medical City - North',
    specialization: 'Senior Obstetrician & Fetal Medicine Specialist',
    sub_specialties: ['High-Risk Antenatal Care', 'Target Scans', 'Painless Labor & Delivery'],
    experience_years: 15,
    opd_timings: '10:00 AM - 02:00 PM (Mon - Sat)',
    room_number: 'North Maternity - Suite 207',
    consultation_fee: 800,
    languages: ['English', 'Hindi', 'Kannada'],
    rating: 4.92,
    total_patients: 11800,
    bio: 'Dedicated to safe maternal deliveries and non-invasive prenatal testing.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 27,
    doctor_name: 'Dr. Sameer Alva',
    degrees: 'MBBS, MD (Dermatology), DNB',
    department_id: 9,
    department_name: 'Dermatology & Cosmetology',
    hospital_id: 3,
    hospital_name: 'RH Care Super-Specialty Medical City - North',
    specialization: 'Consultant Dermatosurgeon & Laser Specialist',
    sub_specialties: ['Vitiligo Surgery', 'Hair Loss PRP', 'Laser Hair Removal'],
    experience_years: 12,
    opd_timings: '02:00 PM - 06:00 PM (Mon - Fri)',
    room_number: 'North Derma - Suite 115',
    consultation_fee: 750,
    languages: ['English', 'Kannada', 'Hindi'],
    rating: 4.89,
    total_patients: 7900,
    bio: 'Focuses on clinical dermatosurgery, scar revision, and hair restorative therapies.',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80'
  },

  // ==========================================
  // CAMPUS 4: Women & Children's Super-Specialty Hospital - South (Jayanagar)
  // ==========================================
  {
    id: 28,
    doctor_name: 'Dr. Ananya Sengupta',
    degrees: 'MBBS, MD (Pediatrics), DCH, DNB (Neonatology), MRCPCH (London)',
    department_id: 4,
    department_name: 'Pediatrics & Neonatology',
    hospital_id: 4,
    hospital_name: "RH Care Women & Children's Super-Specialty Hospital - South",
    specialization: 'Chief of Pediatrics & Level III Neonatal Critical Care',
    sub_specialties: ['Extreme Preterm Neonatal Care', 'Pediatric Pulmonology & Allergy', 'Growth & Developmental Assessment'],
    experience_years: 15,
    opd_timings: '09:00 AM - 01:00 PM (Mon - Sat)',
    room_number: 'Pediatric Pavilion - Room 108',
    consultation_fee: 800,
    languages: ['English', 'Bengali', 'Hindi', 'Kannada'],
    rating: 4.97,
    total_patients: 13500,
    bio: 'Passionate clinician dedicated to newborn survival and infant development. Over 15 years leading Level III NICU.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 29,
    doctor_name: 'Dr. Suniti Deshmukh',
    degrees: 'MBBS, MD (Obstetrics & Gynecology), FICOG, FMAS, Robotic Gyn Fellow',
    department_id: 5,
    department_name: 'Gynecology & Obstetrics',
    hospital_id: 4,
    hospital_name: "RH Care Women & Children's Super-Specialty Hospital - South",
    specialization: 'Director of Maternal-Fetal Medicine & Robotic Gynecology',
    sub_specialties: ['High-Risk Maternal Obstetrics', 'Laparoscopic Myomectomy', 'Natural Orifice Surgery'],
    experience_years: 17,
    opd_timings: '10:30 AM - 03:00 PM (Mon - Sat)',
    room_number: 'Maternal Health - Suite 202',
    consultation_fee: 850,
    languages: ['English', 'Marathi', 'Hindi', 'Kannada'],
    rating: 4.93,
    total_patients: 15000,
    bio: 'Guided over 7,500 safe deliveries with a special emphasis on natural physiological birth and minimally invasive gynecology.',
    image: 'https://images.unsplash.com/photo-1594824813576-24869c98687b?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 30,
    doctor_name: 'Dr. Preeti Singhania',
    degrees: 'MBBS, MD (Dermatology), Fellow in Pediatric Dermatology (USA)',
    department_id: 9,
    department_name: 'Dermatology & Cosmetology',
    hospital_id: 4,
    hospital_name: "RH Care Women & Children's Super-Specialty Hospital - South",
    specialization: 'Senior Consultant Pediatric & Maternal Dermatologist',
    sub_specialties: ['Infant Atopic Dermatitis', 'Pregnancy Dermatoses', 'Laser Therapy for Birthmarks'],
    experience_years: 13,
    opd_timings: '01:30 PM - 05:30 PM (Mon - Fri)',
    room_number: 'Derma Wing - Room 105',
    consultation_fee: 750,
    languages: ['English', 'Hindi', 'Kannada'],
    rating: 4.91,
    total_patients: 8900,
    bio: 'Specialist in pediatric vascular birthmarks, eczema management, and maternal skin protocols.',
    image: 'https://images.unsplash.com/photo-1594824813576-24869c98687b?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 31,
    doctor_name: 'Dr. Kavitha Rajan',
    degrees: 'MBBS, MD (Gen Med), Fellowship in Adolescent & Women Health',
    department_id: 7,
    department_name: 'Internal Medicine & Diabetology',
    hospital_id: 4,
    hospital_name: "RH Care Women & Children's Super-Specialty Hospital - South",
    specialization: 'Senior Consultant in Adult & Adolescent Internal Medicine',
    sub_specialties: ['Gestational Diabetes', 'Thyroid in Pregnancy', 'Adult Immunizations'],
    experience_years: 14,
    opd_timings: '09:00 AM - 01:00 PM (Mon - Sat)',
    room_number: 'Med Suite - Room 201',
    consultation_fee: 750,
    languages: ['English', 'Tamil', 'Kannada', 'Hindi'],
    rating: 4.89,
    total_patients: 9900,
    bio: 'Dedicated physician addressing chronic illness management, endocrine balance, and maternal medical wellness.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 32,
    doctor_name: 'Dr. Anand Ramanathan',
    degrees: 'MBBS, MD (Cardiology), Fellowship in Fetal & Pediatric Cardiology',
    department_id: 1,
    department_name: 'Cardiology',
    hospital_id: 4,
    hospital_name: "RH Care Women & Children's Super-Specialty Hospital - South",
    specialization: 'Senior Consultant Fetal & Pediatric Cardiologist',
    sub_specialties: ['Fetal Echocardiography', 'Newborn Heart Murmur Evaluation', 'Congenital Disease Surveillance'],
    experience_years: 16,
    opd_timings: '10:00 AM - 02:00 PM (Mon - Fri)',
    room_number: 'Fetal Heart - Suite 109',
    consultation_fee: 850,
    languages: ['English', 'Tamil', 'Kannada', 'Hindi'],
    rating: 4.93,
    total_patients: 9400,
    bio: 'Expertise in early prenatal screening of cardiac defects, fetal echo, and post-birth medical interventions.',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 33,
    doctor_name: 'Dr. Shweta Bharadwaj',
    degrees: 'MBBS, DM (Neurology), Fellowship in Pediatric Neurology',
    department_id: 2,
    department_name: 'Neurology & Neurosurgery',
    hospital_id: 4,
    hospital_name: "RH Care Women & Children's Super-Specialty Hospital - South",
    specialization: 'Senior Pediatric Neurologist & Developmental Neuro-Specialist',
    sub_specialties: ['Pediatric Epilepsy & EEG', 'Cerebral Palsy Rehabilitation', 'Autism & ADHD Guidance'],
    experience_years: 12,
    opd_timings: '09:00 AM - 01:00 PM (Mon - Sat)',
    room_number: 'Child Neuro - Suite 206',
    consultation_fee: 800,
    languages: ['English', 'Hindi', 'Kannada'],
    rating: 4.92,
    total_patients: 8700,
    bio: 'Clinical specialist in childhood neurological disorders, neuro-rehab, and dietary therapy for intractable seizures.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 34,
    doctor_name: 'Dr. Vivek Srinivas',
    degrees: 'MBBS, MS (Ortho), Fellowship in Pediatric Orthopedics',
    department_id: 3,
    department_name: 'Orthopedics & Joint Care',
    hospital_id: 4,
    hospital_name: "RH Care Women & Children's Super-Specialty Hospital - South",
    specialization: 'Senior Pediatric Orthopedic Surgeon',
    sub_specialties: ['Clubfoot Ponseti Management', 'Hip Dysplasia (DDH)', 'Pediatric Limb Deformity'],
    experience_years: 14,
    opd_timings: '02:00 PM - 06:00 PM (Mon - Fri)',
    room_number: 'Pediatric Ortho - Room 303',
    consultation_fee: 800,
    languages: ['English', 'Kannada', 'Hindi'],
    rating: 4.90,
    total_patients: 8900,
    bio: 'Gentle corrective orthopedics for children, clubfoot casting, and sports medicine for adolescents.',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 35,
    doctor_name: 'Dr. Manish Chawla',
    degrees: 'MBBS, MS, MCh (Pediatric Surgery)',
    department_id: 6,
    department_name: 'General & Robotic Surgery',
    hospital_id: 4,
    hospital_name: "RH Care Women & Children's Super-Specialty Hospital - South",
    specialization: 'Chief Pediatric Surgeon & Neonatal Minimal Access Surgeon',
    sub_specialties: ['Neonatal Congenital Anomaly Repair', 'Pediatric Laparoscopy', 'Hernia & Hydrocele Day-Care'],
    experience_years: 18,
    opd_timings: '10:00 AM - 02:00 PM (Mon - Sat)',
    room_number: 'Pediatric Surgery - Suite 104',
    consultation_fee: 850,
    languages: ['English', 'Hindi', 'Punjabi', 'Kannada'],
    rating: 4.94,
    total_patients: 11000,
    bio: 'Renowned pediatric surgeon with over 4,000 successful congenital reconstructive surgeries.',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 36,
    doctor_name: 'Dr. Leena Thomas',
    degrees: 'MBBS, MS (ENT), Fellowship in Pediatric Otolaryngology',
    department_id: 8,
    department_name: 'ENT & Head Neck Surgery',
    hospital_id: 4,
    hospital_name: "RH Care Women & Children's Super-Specialty Hospital - South",
    specialization: 'Senior Pediatric ENT Surgeon',
    sub_specialties: ['Coblation Adenotonsillectomy', 'Glue Ear & Grommet Insertion', 'Pediatric Airway Stridor'],
    experience_years: 13,
    opd_timings: '03:00 PM - 06:30 PM (Mon - Sat)',
    room_number: 'Child ENT - Room 111',
    consultation_fee: 750,
    languages: ['English', 'Malayalam', 'Hindi', 'Kannada'],
    rating: 4.91,
    total_patients: 8600,
    bio: 'Specialist in minimally invasive pediatric ear, nose, and throat procedures.',
    image: 'https://images.unsplash.com/photo-1594824813576-24869c98687b?auto=format&fit=crop&w=600&q=80'
  },

  // ==========================================
  // CAMPUS 5: Institute of Neurosciences & Orthopedics - West (Rajajinagar)
  // ==========================================
  {
    id: 37,
    doctor_name: 'Dr. Alok Chandra',
    degrees: 'MBBS, MS (Orthopedics), Spine Surgery Fellowship (Munich)',
    department_id: 3,
    department_name: 'Orthopedics & Joint Care',
    hospital_id: 5,
    hospital_name: 'RH Care Institute of Neurosciences & Orthopedics - West',
    specialization: 'Senior Consultant Spine & Deformity Correction Surgeon',
    sub_specialties: ['Endoscopic Spine Decompression', 'Minimally Invasive Spine Fusion', 'Scoliosis Correction', 'Cervical Disc Replacement'],
    experience_years: 16,
    opd_timings: '02:00 PM - 06:30 PM (Mon - Sat)',
    room_number: 'Spine Pavilion - Suite 102',
    consultation_fee: 850,
    languages: ['English', 'Hindi', 'Bengali', 'Kannada'],
    rating: 4.89,
    total_patients: 11000,
    bio: 'Excellence in day-care endoscopic microdiscectomy and complex 3D image-guided spine navigation.',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 38,
    doctor_name: 'Dr. Vijayalakshmi Narayan',
    degrees: 'MBBS, MCh (Neurosurgery) - NIMHANS, Fellowship in Skull Base Surgery',
    department_id: 2,
    department_name: 'Neurology & Neurosurgery',
    hospital_id: 5,
    hospital_name: 'RH Care Institute of Neurosciences & Orthopedics - West',
    specialization: 'Senior Consultant Neurosurgeon & Spine Specialist',
    sub_specialties: ['Brain Tumor Surgery', 'Cerebrovascular Aneurysm Clipping', 'Spinal Cord Tumors'],
    experience_years: 18,
    opd_timings: '09:00 AM - 01:30 PM (Mon - Sat)',
    room_number: 'West Neuro - Suite 201',
    consultation_fee: 950,
    languages: ['English', 'Kannada', 'Tamil', 'Hindi'],
    rating: 4.95,
    total_patients: 12800,
    bio: 'Alumna of NIMHANS with mastery in intraoperative neuro-navigation, awake craniotomy, and endoscopic pituitary resection.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 39,
    doctor_name: 'Dr. Narendra Somani',
    degrees: 'MBBS, MD (Medicine), DM (Cardiology)',
    department_id: 1,
    department_name: 'Cardiology',
    hospital_id: 5,
    hospital_name: 'RH Care Institute of Neurosciences & Orthopedics - West',
    specialization: 'Senior Consultant Cardiologist & Echo Specialist',
    sub_specialties: ['Non-Invasive Cardiology', 'Stress Echocardiography', 'Preventive Cardiology'],
    experience_years: 15,
    opd_timings: '02:00 PM - 06:00 PM (Mon - Sat)',
    room_number: 'West Cardio - Room 108',
    consultation_fee: 800,
    languages: ['English', 'Hindi', 'Gujarati', 'Kannada'],
    rating: 4.88,
    total_patients: 11200,
    bio: 'Expertise in early cardiovascular disease detection, non-invasive imaging, and perioperative clearance.',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 40,
    doctor_name: 'Dr. Joseph Mathew',
    degrees: 'MBBS, MD (Internal Medicine)',
    department_id: 7,
    department_name: 'Internal Medicine & Diabetology',
    hospital_id: 5,
    hospital_name: 'RH Care Institute of Neurosciences & Orthopedics - West',
    specialization: 'Senior Consultant Physician',
    sub_specialties: ['Infectious Diseases', 'Adult Chronic Illness', 'Fever & Critical Care Medicine'],
    experience_years: 17,
    opd_timings: '09:00 AM - 01:00 PM (Mon - Sat)',
    room_number: 'West Suite - Room 102',
    consultation_fee: 750,
    languages: ['English', 'Malayalam', 'Hindi', 'Kannada'],
    rating: 4.89,
    total_patients: 13900,
    bio: 'Comprehensive internal medicine consultant with two decades in diagnosis of multi-system illnesses.',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 41,
    doctor_name: 'Dr. Meenakshi S. Iyer',
    degrees: 'MBBS, MD (Dermatology & Leprosy), Fellowship in Aesthetic Laser Surgery',
    department_id: 9,
    department_name: 'Dermatology & Cosmetology',
    hospital_id: 5,
    hospital_name: 'RH Care Institute of Neurosciences & Orthopedics - West',
    specialization: 'Senior Consultant Dermatologist & Trichologist',
    sub_specialties: ['Biological Therapy for Psoriasis', 'Fractional CO2 Laser & Scar Revision', 'Hair Restoration & PRP'],
    experience_years: 12,
    opd_timings: '11:00 AM - 04:00 PM (Mon - Fri)',
    room_number: 'Dermatology Clinic - Suite 112',
    consultation_fee: 750,
    languages: ['English', 'Tamil', 'Hindi', 'Kannada'],
    rating: 4.90,
    total_patients: 9200,
    bio: 'Known for evidence-based dermatological clinical therapy and state-of-the-art cosmetic laser interventions.',
    image: 'https://images.unsplash.com/photo-1594824813576-24869c98687b?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 42,
    doctor_name: 'Dr. Vinay Kumar G.',
    degrees: 'MBBS, MS (General Surgery), Fellowship in Minimal Access Surgery',
    department_id: 6,
    department_name: 'General & Robotic Surgery',
    hospital_id: 5,
    hospital_name: 'RH Care Institute of Neurosciences & Orthopedics - West',
    specialization: 'Senior Consultant General & Laparoscopic Surgeon',
    sub_specialties: ['Laparoscopic Appendectomy', 'Hernioplasty', 'Gallbladder Surgery'],
    experience_years: 15,
    opd_timings: '10:00 AM - 02:00 PM (Mon - Sat)',
    room_number: 'West Surgery - Room 204',
    consultation_fee: 800,
    languages: ['English', 'Kannada', 'Hindi'],
    rating: 4.88,
    total_patients: 10200,
    bio: 'Specialist in day-care laparoscopic procedures and soft tissue surgical care.',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 43,
    doctor_name: 'Dr. Suhasini Patil',
    degrees: 'MBBS, DCH, DNB (Pediatrics)',
    department_id: 4,
    department_name: 'Pediatrics & Neonatology',
    hospital_id: 5,
    hospital_name: 'RH Care Institute of Neurosciences & Orthopedics - West',
    specialization: 'Consultant Pediatrician & Adolescent Physician',
    sub_specialties: ['Newborn Checkups', 'Childhood Infections', 'Immunization Protocols'],
    experience_years: 11,
    opd_timings: '09:00 AM - 01:00 PM (Mon - Sat)',
    room_number: 'West Child Clinic - Room 107',
    consultation_fee: 700,
    languages: ['English', 'Kannada', 'Marathi', 'Hindi'],
    rating: 4.89,
    total_patients: 8200,
    bio: 'Dedicated child health practitioner focusing on preventive pediatric care.',
    image: 'https://images.unsplash.com/photo-1594824813576-24869c98687b?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 44,
    doctor_name: 'Dr. Bharathi Murthy',
    degrees: 'MBBS, MS (OBG), DGO',
    department_id: 5,
    department_name: 'Gynecology & Obstetrics',
    hospital_id: 5,
    hospital_name: 'RH Care Institute of Neurosciences & Orthopedics - West',
    specialization: 'Senior Obstetrician & Gynecological Surgeon',
    sub_specialties: ['Routine & High-Risk Antenatal Care', 'Fibroid Uterus Management', 'Well-Woman Health'],
    experience_years: 16,
    opd_timings: '02:00 PM - 06:00 PM (Mon - Fri)',
    room_number: 'West Women Clinic - Suite 203',
    consultation_fee: 800,
    languages: ['English', 'Kannada', 'Telugu', 'Hindi'],
    rating: 4.92,
    total_patients: 10800,
    bio: 'Comprehensive women’s health clinician committed to personalized maternity and gynecological care.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 45,
    doctor_name: 'Dr. Sunil K. Devadiga',
    degrees: 'MBBS, MS (ENT), DNB',
    department_id: 8,
    department_name: 'ENT & Head Neck Surgery',
    hospital_id: 5,
    hospital_name: 'RH Care Institute of Neurosciences & Orthopedics - West',
    specialization: 'Senior ENT Surgeon',
    sub_specialties: ['Micro-Laryngeal Surgery', 'Endoscopic Sinus Surgery', 'Hearing Rehabilitation'],
    experience_years: 14,
    opd_timings: '09:30 AM - 01:30 PM (Mon - Sat)',
    room_number: 'West ENT - Room 116',
    consultation_fee: 750,
    languages: ['English', 'Kannada', 'Hindi'],
    rating: 4.90,
    total_patients: 9100,
    bio: 'Expertise in vertigo diagnosis, allergic rhinitis, and precision microscopic ear surgery.',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80'
  }
];

export const initialPatients: Patient[] = [
  { id: 1, name: 'Ramesh Patel', phone: '+91 98450 12345', age: 54, gender: 'Male', date: '2026-09-24', address: '124, 12th Main Road, Indiranagar, Bengaluru', created_at: new Date().toISOString() },
  { id: 2, name: 'Sunita Rao', phone: '+91 98860 67890', age: 46, gender: 'Female', date: '2026-09-25', address: '45, Palm Meadows, Whitefield, Bengaluru', created_at: new Date().toISOString() },
  { id: 3, name: 'David Miller', phone: '+91 99001 23456', age: 38, gender: 'Male', date: '2026-09-26', address: '78, Defence Colony, Hebbal, Bengaluru', created_at: new Date().toISOString() },
  { id: 4, name: 'Farhan Khan', phone: '+91 97410 98765', age: 29, gender: 'Male', date: '2026-09-27', address: '12, 5th Block, Jayanagar, Bengaluru', created_at: new Date().toISOString() }
];

export const initialAppointments: Appointment[] = [
  {
    id: 1,
    patient_id: 1,
    doctor_id: 1,
    hospital_id: 1,
    appointment_date: '2026-09-24',
    appointment_time: '10:30 AM',
    token_number: 'RH-2026-0841',
    status: 'Approved',
    created_at: new Date().toISOString(),
    patient_name: 'Ramesh Patel',
    patient_phone: '+91 98450 12345',
    patient_age: 54,
    patient_address: '124, 12th Main Road, Indiranagar, Bengaluru',
    doctor_name: 'Dr. R. Rajeshwar',
    specialization: 'Director & Chief Interventional Cardiologist',
    department_name: 'Cardiology',
    hospital_name: 'RH Care Multi-Specialty Hospital - Central Campus',
    hospital_address: '14/2, 100 Feet Road, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560038',
    distance_km: 0.8,
    symptoms: 'Chest tightness upon exertion, preventive cardiac evaluation'
  }
];

export const initialAdmins: Admin[] = [
  {
    id: 1,
    username: 'admin',
    password: bcrypt.hashSync('admin123', 10)
  }
];
